services:
  - type: web
    name: hugo-betting-site
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    envVars:
      - key: HUGO_VERSION
        value: 0.121.1
    buildFilter:
      paths:
        - assets/**
        - content/**
        - layouts/**
        - static/**
        - config.toml
        - package.json
        - postcss.config.js
        - tailwind.config.js 